---
- name: Cambiar hostname de la máquina
  hosts: student1-win1

  tasks:
    - name: Cambiar el hostname
      win_hostname:
        name: NombreDePrueba


    - name: Reboot
      win_reboot:

      

    
    - name: Show hostname
      debug:
         msg: "This is the hostname: {{ ansible_hostname }}"