---
- name: Create a directory in windows
  hosts: student1-win1
  gather_facts: false

  tasks:
    - name: Create directory /tmp/reto1
      win_file:
        path: C:\tmp\reto1
        state: directory