- name: Take backup and add content to archive
  hosts: student1-win1

  tasks:
    - name: Take backup of file
      win_copy:
        src: C:\tmp\reto1\reto1_content
        dest: C:\tmp\reto1\reto1_content_back
        remote_src: yes

    - name: Add content to file
      win_lineinfile:
        path: C:\tmp\reto1\reto1_content
        line: "ESTA ES UNA PRUEBA"
        create: yes
        insertafter: EOF